# deployment.yaml

apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-react-app-deployment
spec:
  replicas: 2 # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: my-react-app 
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
      - name: my-react-app
        image: 07dilip/my-react-app:02  # Use your Docker image name and tag
        ports:
        - containerPort: 3000



